/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: KaramellGlass (https://sketchfab.com/KaramellGlass)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cap-3a3bb4aa2e284e98b9f761defc6a8f4a
title: Cap
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Cap(props) {
  const group = useRef();
  useEffect(() => {
    if (group && group.current) {
      // setInterval(() => {
      //   group.current.rotation.y += 0.01;
      //   group.current.rotation.x += 0.01;
      //   group.current.rotation.z += 0.01;
      // });
    }

    return () => {};
  }, [group]);
  const { nodes, materials } = useGLTF("/cap/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object016__0.geometry}
              material={materials["Scene_-_Root"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/cap/scene.gltf");
